name: CICD
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name : Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build project
        run: mvn clean install -Dmaven.test.skip
      - name: Docker Login
        run: docker login -u ${{secrets.DOCKHUB_UID}} -p ${{secrets.DOCKHUB_PWD}}
      - name: Build docker image
        run: docker build -t itzmedinesh/movie-search-service .
      - name: Push image to docker hub
        run: docker push itzmedinesh/movie-search-service:latest

  deploy:
    needs: build
    runs-on: [msrunner]
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull itzmedinesh/movie-search-service:latest
      - name: Delete container if exists
        run: sudo docker rm -f movie-search-container
      - name: Run as container
        run: sudo docker run -d -p 8090:8090 --name movie-search-container itzmedinesh/movie-search-service
